name: Elixir CI

on: push

jobs:
  elixir:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: 1.14.3
          otp-version: 25.2.2

      - name: Install dependencies
        run: |
          cd backend
          mix deps.get

      - name: Run tests
        run: |
          cd backend
          mix test

      - name: Run credo
        run: |
          cd backend
          mix credo --strict

      - name: Compile issues
        run: |
          cd backend
          mix compile --warnings-as-errors

      # TODO(sabit): add dialyxir library to run this.
      # - name: Dialyzer
      #   run: |
      #     cd backend
      #     mix dialyzer

      - name: Check code is properly formatted
        run: |
          cd backend 
          mix format --check-formatted
