name: Elixir CI

on: push

jobs:
  elixir:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: 1.14.3
          otp-version: 25.2.2

      - name: Install dependencies
        run: |
          cd blog-application/backend
          mix deps.get

      - name: Run tests
        run: |
          cd blog-application/backend
          mix test

      - name: Run credo
        run: |
          cd blog-application/backend
          mix credo --strict

      - name: Compile issues
        run: |
          cd blog-application/backend
          mix compile --warnings-as-errors

      # TODO(sabit): add dialyxir library to run this.
      # - name: Dialyzer
      #   run: |
      #     cd blog-application/backend
      #     mix dialyzer

      - name: Check code is properly formatted
        run: cd blog-application/backend mix format --check-formatted
